### ISSUE TITLE
Authr-ClientPin1-GetKeyAgreement P-1: #237 is not solved

### ISSUE THREAD

**Issue by eugenIFX** [fido-alliance/conformance-tools-issues#268]
## What protocol and version of the protocol are you testing?

FIDO2 v1.0

## What is your implementation class?

Authr

## What is the version of the tool are you using?
0.9.422

## What is the OS and the version are you running?
Windows 7 64-bit

## Issue description
@herrjemand , regarding #237 issue, will be the spec updated to make the alg mandatory, or you can remove it from the tests? Currently, is required by the test tool.

**Comment by herrjemand** [comment]
@eugenIFX So per discussion at the plenary: We are working to register new value. So for now we follow specs: this field is mandatory, but we are not mandating specific value. So it has to be presented, has to be set to some value, but we are not specifying what exact value. I would recommend setting it to -25 since everyone else does that, but I am not checking with the tool.
