### ISSUE TITLE
Server-ServerAuthenticatorAttestationResponse-Resp-9 P-3

### ISSUE THREAD

**Issue by aseigler** [fido-alliance/conformance-tools-issues#396]
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

v0.10.109

## What is the OS and the version are you running?

Windows 10

## Issue description

P-3 Send a valid ServerAuthenticatorAttestationResponse with "tpm" attestation pubArea.nameAlg is not matching algorithm used for generate attested.name, and check that server succeeds

Spec (https://www.w3.org/TR/webauthn/#tpm-attestation) states:

"Verify that attested contains a TPMS_CERTIFY_INFO structure as specified in [TPMv2-Part2] section 10.12.3, whose name field contains a valid Name for pubArea, as computed using the algorithm in the nameAlg field of pubArea using the procedure specified in [TPMv2-Part1] section 16."

Test appears contrary to spec, in spirit allowing valid Name for pubArea as computed using algorithm in the attestation statement instead of nameAlg field of pubArea as specified.

**Comment by herrjemand** [comment]
Sorry for the delay. I was traveling.

> name field contains a valid Name for pubArea, as computed using the algorithm in the nameAlg field of pubArea using the procedure specified in [TPMv2-Part1] section 16.

So the name is concatenation of nameAlg[2byte] and hash structure[n-bytes].

The confusion comes from the fact TPMS_CERTIFY_INFO contains name field  that contains name of the TPMT_PUBLIC. But in the same time TPMT_PUBLIC contain nameAlg field that contains algorithm identifier for calculating authPolicy. There two both use nameAlg, but they can be different.

For example:
TPMT_PUBLIC.nameAlg = SHA-1;
TPMT_PUBLIC.authPolicy = hash[TPMT_PUBLIC.nameAlg](TPMU_AUTH_POLICY)

nameAlg = SHA-256
TPMS_CERTIFY_INFO.name = nameAlg || hash[nameAlg](TPMT_PUBLIC)

Does this makes more sense @aseigler ?

**Comment by aseigler** [comment]
So the nameAlg that is IN pubArea, is not the nameAlg field OF pubArea, that nameAlg is for the policy.  Rather, the nameAlg in the TPMS_CERTIFY_INFO is OF pubArea and is therefore the one used to verify.  That is extremely confusing wording, but it works.

**Comment by aseigler** [comment]
Still makes more sense than CSS.

**Comment by herrjemand** [comment]
![giphy 2](https://user-images.githubusercontent.com/1636116/46240525-8f0c4400-c3db-11e8-92e5-2f9a49ddb395.gif)

**Comment by madwizard-thomas** [comment]
I ran into this too, it makes sense to use the prefixed algorithm identifier from certify_info.name rather than the one in pubArea.nameAlg, but I still fail to see how the wording in the W3 specs can be interpreted to do that:
> ... whose name field contains a valid Name for **pubArea**, as computed using the algorithm in the **nameAlg** field of **pubArea**

Doesn't this explicitly say to use pubArea.nameAlg to compute the name? If the sentence ended after "whose name field contains a valid Name for pubArea" it would make more sense. 

Also your own article on [TPM verification](https://medium.com/@herrjemand/verifying-fido-tpm2-0-attestation-fc7243847498) seems to use pubArea.nameAlg as well:
 >9. Hash pubArea to create pubAreaHash using the pubArea.nameAlg
> 10. Concatenate pubArea.nameAlg and pubAreaHash to create attestedName.
> 11. Check that certInfo.attested.name is equals to attestedName.
If certInfo.attested.name contains it own algorithm there can be multiple valid names using different algorithms and a comparison like this would not suffice.

Also earlier the article's description of TPMT_PUBLIC seems to indicate the algorithms must be the same:
> name alg — an algorithm that was used to generate name field in certInfo. Must much algorithm in name [sic, 'match' was intended I presume?]

**Comment by grzuy** [comment]
Hi @herrjemand,

Sorry I am still trying to understand how Name computation works and how it can be possible for the hash algorithms to be different in both structures, based on TPM 2.0 spec.

> Sorry for the delay. I was traveling.
> 
> > name field contains a valid Name for pubArea, as computed using the algorithm in the nameAlg field of pubArea using the procedure specified in [TPMv2-Part1] section 16.
> 
> So the name is concatenation of nameAlg[2byte] and hash structure[n-bytes].
> 
> The confusion comes from the fact TPMS_CERTIFY_INFO contains name field that contains name of the TPMT_PUBLIC. But in the same time TPMT_PUBLIC contain nameAlg field that contains algorithm identifier for calculating authPolicy.

Section `12.2.4 TPMT_PUBLIC` in [TPM-Rev-2.0-Part-2-Structures](https://www.trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-2-Structures-01.38.pdf) mentions that `TPMT_PUBLIC.nameAlg` is both used for authPolicy (as you mentioned above) and ___for computing the Name of the object___.

![image](https://user-images.githubusercontent.com/456459/73684289-9e239600-46a2-11ea-8716-afcdd952b8e0.png)

> There two both use nameAlg, but they can be different.

Is there any passage in the TPM 2.0 spec that explicitly mentions, or you think it can be inferred, that there's a possibility that `TPMT_PUBLIC.nameAlg` and `TPMS_CERTIFY_INFO.name.name.hashAlg` can be different?

Honestly asking because I couldn't, and I might be missing something in the sea of TPM docs :-)

Passages from the TPM docs that make me think that the `TPMS_CERTIFY_INFO.name.name.hashAlg` __has to be the same__ as in `TPMT_PUBLIC.nameAlg`, because one is computed from the other, are:


1. `Table 3 — Equations for Computing Entity Names` in [TPM-Rev-2.0-Part-1-Architecture](https://www.trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-1-Architecture-01.38.pdf) where it states that for Objects the hash structure of the Name is computed _"using the_ ___nameAlg parameter in the object___ _associated with handle"_, were handle is referring to the public area (TPMT_PUBLIC), i.e. `TPMT_PUBLIC.nameAlg` from what I understand.

![image](https://user-images.githubusercontent.com/456459/73685603-328ef800-46a5-11ea-8e08-189f209cdfbb.png)


2. Section `16 Names` in [TPM-Rev-2.0-Part-1-Architecture](https://www.trustedcomputinggroup.org/wp-content/uploads/TPM-Rev-2.0-Part-1-Architecture-01.38.pdf) stating:

_"__The  Name  of  an  entity  is  its  unique  identifier.___  _The  handle  associated  with  an  object  may  change  due  to  context management (TPM2_ContextSave() / TPM2_ContextLoad()),_ ___but the Name of an object remains constant__"_.

Assuming that `TPMS_CERTIFY_INFO.name.name.hashAlg` can be different from `TPMT_PUBLIC.nameAlg`, that would mean there could be two valid and different names for the same object, which contradicts the statement from the TPM spec above, in my opinion.

My deduction here being, `TPMS_CERTIFY_INFO.name.name.hashAlg` has to have the same hash algorithm as `TPMT_PUBLIC.nameAlg` in order for the Name of a public area to be unique.

This is a similar argument to what @madwizard-thomas stated in https://github.com/fido-alliance/conformance-tools-issues/issues/396#issuecomment-471320778.

> 
> For example:
> TPMT_PUBLIC.nameAlg = SHA-1;
> TPMT_PUBLIC.authPolicy = hash[TPMT_PUBLIC.nameAlg](TPMU_AUTH_POLICY)
> 
> nameAlg = SHA-256
> TPMS_CERTIFY_INFO.name = nameAlg || hash[nameAlg](TPMT_PUBLIC)
> 
> Does this makes more sense @aseigler ?

Sorry for the long comment, and thanks in advance!
