### ISSUE TITLE
UAF v1.1 - TrustedFacets.version

### ISSUE THREAD

**Issue by mirkop** [fido-alliance/conformance-tools-issues#482]
## What protocol and version of the protocol are you testing?

UAF v1.1

## What is your implementation class?
Client/ASM+Authr

## What is the version of the tool are you using?
v1.4.4

## What is the OS and the version are you running?
iOS 12.3.1

## Issue description
When running tests for UAF v1.1 and obtaining the TrustedFacets list. The TrustedFacets.version is always set to ```"version":{"major":1,"minor":0}```. The FIDO AppID and Facet Specification says "From among the objects in the trustedFacet array, select the one with the version matching that of the protocol message version." The UAF protocol version (upv) of the UAF Protocol message is ```version":{"major":1,"minor":1}``` for UAF v1.1.

*Shouldn't the conformance test's trustedFacets.version be using 1.1? If not, what is the TrustedFacets.version value supposed to be based on?*

````javascript
{
  "trustedFacets": [
    {
      "version": { "major": 1, "minor": 0 },
      "ids": [
        "ios:bundle-id:org.fidoalliance.mobile.conformancetools",
        "https://fidoalliance.nz/"
      ]
    }
  ]
}
````

**Comment by herrjemand** [comment]
TFL is 1.0 right now. The structure has not been updated. UPV for TFL is not the same as for UAF protocol messages.

**Comment by mirkop** [comment]
The FIDO AppID and Facet Specifications are wrong then if the version identifies the TFL structure version. The FIDO AppID and Facet Specification says "From among the objects in the trustedFacet array, select the one with the version matching that of the protocol message version."

**Comment by danielkummer** [comment]
Trusted facets version = UAF Protocol Version
UPV Version != UAF Protocol Version

**Comment by talaieru** [comment]
To me as mentioned by @mirkop the specification is quite explicit, the version of the FIDO UAF protocol is the one to be used.

What would be the point of having an array, where each element groups all the facets associated with a version, if the version refers to the version of the Trusted Facets Specification (which is unique)?

On the other hand, using the FIDO UAF protocol version makes a lot more of sense: it allows a server to support several FIDO UAF protocols and exposing this compatibility in the Facets.  The application cares about the whole set protocol messages that the server is compatible with (and this includes the faces messages, which are part of the FIDO UAF 1.1 even though the remain the same as in FIDO UAF 1.0).

The fact that the format of the trusted facets (i.e. its specification) does not change (or at least remains backwards compatible) across FIDO UAF versions makes a lot of sense because it helps supporting several versions of the FIDO UAF protocol in both the client and the server (by exposing the FIDO UAF protocol on it).
